language: go
go:
- 1.13
jobs:
  include:
  - stage: test
    name: "Unit Tests"
    script: go test -v ./...
  - stage: build
    name: "Compile"
    script:
    - mkdir dist
    - go build -o dist/goldfrogd cmd/goldfrogd/main.go
  - stage: deploy
    name: "Push to S3"
    script: "./deploy"

# before_deploy:
# - tar -zcf dist/goldfrogd.tar.gz dist/goldfrogd

# deploy:
#   provider: s3
#   file: dist/goldfrogd.tar.gz
#   cleanup: false
#   secret_access_key:
#     secure: t119V4VRvObqCIqyGyyRzb0f0K3lOm5RFgkTYAACqzAXID0SVhg0g1G5o5y3fvgWk8sb88nAe3V8PJ6n9YOVqalGKRSV8x5hsRMgsJsfH2bNAOGc7eZLhHR3uwF4CfWzcrPcrNAzVD1hRW8A5X/khbc4YtclljW+0sWjbiP+Ks1psAhasTM+ojhJrq/wYCnEay8vszF0Jx4YE/WFO0RS1Bnim4I6jQ8hbWYh3BcMMF8ACtJp7QoCQt3/hwvjDijm1syJPeY1ALcXbm3d8vlzRFXGESVb44dsxzl6NcozZVZfSL1nclBnSTwnWN5fbjkXPGoMKt5eQ02lJakXlJnvCSje/CCXihBkZnfW+7AfCsL7K5oFyr7FXN9edK3ukudsU3nVRFv2aWgsVMAsFa2nSO1FHodEBFF6S63ffVMlP2VzyU3fAuLMqa9/6Vz9VXssCbB0bCvohlPDc+zpgHfSDGxPejNKbbN9xt4IthzpyWOSbKGsf0c/B8Ajsi8o212JrnUTmPykpuhN/bv5s33xKPNhvL3vsD9D1wuFdnJn8tOELpdcRFhGP1NnCV5DtJlWs/i0u1p2Q0yddeDpsM8uggpkRXUjanD71wUHC8gBTwbCzC0bYBMnSrxyFP9VfZSdeSl8eZc3rMa4FF/8E9huTIMMJHAqYlCDA7jYyPsfgPI=
#   access_key_id:
#     secure: IcTVwsWSbi6W5aZWfN551At9RWb/BVr9yhflKSWOAyZFOyYaf150mBReDwzoShdnhgBvJS9ZpffV2DLhzyEbHIeVwC3Gbv3xkyAiJ5Ah8HO80rjwwpWmgVChUDZvAlxbqWgF8E+C9ZfIn1BJAEbzKKX+vL3wFJCcwfz593ezXFNakABXPd8kxlfIn40uApKTiYSO0Cd/03Wi/x3T9cIMdbWVCsLPU9NXQQ/fDS2t9r8KMzTsiO4okTPBrY8OLhtA+MO2vcpH75dt6boNAKICDb+34YkoHODOWdiPc2ZpMlx4hJpwiGZ5YdivlBbQLKwnLcemb2VKchDUsG95PaHD0TKphQF6BAsIf7jVU16oBiOIF+sNvXDxKa+g5D2pB+NJUJbgjhG7EYE2/sXOCP6DzmrtQ+5Jewmg33QUXhiVnyd4Xm9XKDwKOHyLTZ/9TMBfTqQL2EJjkb026AsTACIZsmIJISHGJcBZzpREeAxPquaSKNBe9vjMb+asAdQRVj4Ex/BkpQCgeIPdiqo/N7/shpoaMy7VAmP2BC+xoWDdqlOcG+TEMIm9FzkochyP0qICNXbfvO4oX4wmKqi8RxZUsiNxAv6j+C0rPHbOhbX/XnR14mSnvj86dbGH7sVgerbYF7XT/soP3A273HIO47/5Cdv4zttu55lrP2YTGHrw9cE=
#   bucket: goldfrog-releases
