# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      # get source
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      # build the binary
      - run: mkdir dist
      - run: make server
      - run: make indexer
      - run: ./goldfrogd --version > TAG.txt
      - run: ./goldfrogd --version-long > VERSION.txt
      - persist_to_workspace:
          root: .
          paths:
            - TAG.txt
            - VERSION.txt
            - goldfrogd
            - indexer

  publish-to-s3:
    docker:
      - image: circleci/python:3.7.2
    steps:
      # compress the binaries for distribution
      - attach_workspace:
          at: dist

      # "Long version" (tag-int-hash) package
      - run:
          command: |
            echo "long version"
            cat dist/VERSION.txt
            tar -zcf goldfrog-`cat dist/VERSION.txt`.tgz dist/*

      - run:
          command: sudo pip install awscli

      # publish to s3
      - run:
          command: |
          aws s3 cp VERSION.txt s3://goldfrog-releases --acl public-read
          aws s3 cp goldfrog-latest.tgz s3://goldfrog-releases --acl public-read

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./dist
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat TAG.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - publish-to-s3:
          requires:
            - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/