# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      # get source
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      # build the binary
      - run: mkdir dist
      - run: make server
      - run: make indexer
      - persist_to_workspace:
          root: .
          paths:
            - goldfrogd
            - indexer

  publish-to-s3:
    docker:
      - image: circleci/golang:1.13
    steps:
      # compress the binaries for distribution
      - attach_workspace:
          at: dist


      # "Tag" package
      - run:
          command: |
            echo "short version"
            dist/goldfrogd --version
            tar -zcf goldfrog-`dist/goldfrogd --version`.tgz dist/*
      # "Long version" (tag-int-hash) package
      - run:
          command: |
            echo "long version"
            dist/goldfrogd --version-long
            tar -zcf goldfrog-`dist/goldfrogd --version-long`.tgz dist/*

      # publish to s3
      - run: sudo apt-get -y install python-dev python-pip
      - aws-s3/copy:
          from: "*.tgz"
          to: 's3://goldfrog-releases'
          arguments: |
            --acl public-read

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - publish-to-s3:
          requires:
            - build
