# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - attach_workspace:
          at: ./artifacts

      # get source
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      # build the binary
      - run: mkdir dist
      - run: make server
      - run: make indexer

  publish-to-s3:
    docker:
      - image: circleci/python:3.7.2
    steps:
      # compress the binaries for distribution
      - attach_workspace:
          at: ./artifacts

      - run: tar -zcf goldfrog-`./artifacts/goldfrogd --version`.tgz dist/*

      # publish to s3
      # - run: sudo apt-get install python-dev
      # - run: sudo apt-get install python-pip
      - aws-s3/copy:
          from: goldfrog.tgz
          to: 's3://goldfrog-releases'
          arguments: |
            --acl public-read
          # arguments: '--dryrun'
